const SIS_PROFS = [
    "Abdella, Beth",
    "Adhikari, Prabal",
    "Adolph, Alden",
    "Akimoto, Hiroe",
    "Al Atiyat, Ibtesam",
    "Alderks, Elisabeth G.",
    "Allister, Mark",
    "Amundson, Steven",
    "Ananda-Owens, Kathryn",
    "Anderegg, Francesca",
    "Anderson, Joshua",
    "Anderson, Scott",
    "Angell, Diane K.",
    "Armstrong, Anton",
    "Atzinger, Christopher",
    "Bader, Jennifer",
    "Bansah, Marcus",
    "Barbosa-Jerez, Mary E.",
    "Barjasteh, Jolene",
    "Barnes-Karol, Gwendolyn",
    "Bateza, Anthony",
    "Becker, Anthony",
    "Beckman, Patricia",
    "Beld, Jo M.",
    "Benson, Jessica M.",
    "Benson, Kristell M.",
    "Berliner, Adam H.",
    "Berry, Anne G.",
    "Beussman, Douglas J.",
    "Bi, Hui",
    "Billingsley, Tyler R.",
    "Binder, Seth",
    "Bjorklund, Brian",
    "Bobb, James E.",
    "Boehm, Laura F.",
    "Bolis, Amy L.",
    "Book, Cynthia",
    "Borovsky, Brian",
    "Bosch, Kelsey E.",
    "Bostwick, Christi",
    "Bouxsein, Hilary J.",
    "Bowers, Lisa M.",
    "Brandon, Miranda",
    "Brandwein, Rachel",
    "Bransford, Margaret A.",
    "Breckbill, Anne",
    "Brentrup, Jennifer",
    "Bretscher, Kathryn L.",
    "Brochman, Kevin J.",
    "Broner, Maggie",
    "Brown, Richard",
    "Bucciaglia, Nicolette",
    "Burk, Sarah",
    "Buzza, Timothy D.",
    "Cahoon, Kirsten E.",
    "Campbell, Heather",
    "Carlsen, Mary",
    "Carlson, Susan",
    "Carmes, Megan L.",
    "Carter, David",
    "Casson, Douglas J.",
    "Castro, David R.",
    "Chamseddine, Ali",
    "Chapp, Christopher B.",
    "Charlton, Norma E.",
    "Cherewatuk, Karen",
    "Chiappari, Christopher L.",
    "Cho, Grace E.",
    "Choi, Vivian",
    "Christie, Sian E.",
    "Cilizoglu, Menevis",
    "Cisar, Mary",
    "Claussen, Kurt N.",
    "Clift, Anna",
    "Clifton, Sara",
    "Cole, Eric",
    "Cole, Steven",
    "Conger, Andrea C.",
    "Coughlin, Jenna M.",
    "Crisp, Kevin M.",
    "Cropsey, Kris A.",
    "Cunningham, Arthur",
    "David, Marc",
    "Davila, Jaime I.",
    "DeFries, Brett B.",
    "Dell, Irve",
    "Demas, James",
    "Dickinson, Shelly D.",
    "Dietz, Jill",
    "Dixon, Jeffrey W.",
    "Dorer, Kari L.",
    "Dougherty, Ann",
    "Dowd, Adam J.",
    "Draxler, Bridget A.",
    "Dressen, Dan",
    "Dulkin, Ryan S.",
    "Dworsky, Shoshana",
    "Edwards, Paul D.",
    "Edwards, Todd F.",
    "Eichberger, Ryan C.",
    "Elhard, Julie",
    "Elias, Christopher M.",
    "Elsaesser, Carl",
    "Engbrecht, Jason J.",
    "Engleman, Tracey M.",
    "Epstein, Louis K.",
    "Epstein, Maglen K.",
    "Erickson, Anna",
    "Estenson, Kristine M.",
    "Feldt, Alison J.",
    "Figueroa-Ray, Kelly W.",
    "Fisher, Kathryne",
    "Fitzgerald, Michael",
    "Fleming, Justin H.",
    "Foster, Veronica C.",
    "Frary, Whitney E.",
    "Freedberg, Steven",
    "Fretland, Daniel",
    "Fruehling, Sara E.",
    "Fuerstein, Michael",
    "Fure-Slocum, Eric J.",
    "Fyfe, Charles A.",
    "Gallego, Carlos",
    "Garner, Leigh Ann",
    "Garrett, Kristina",
    "Giannini, John",
    "Gittins, Peter J.",
    "Glampe, Kathy",
    "Goedde, Richard",
    "Gonzalez, Wendy D.",
    "Goodwin, Tracy H.",
    "Gothmann, Anne M.",
    "Granquist, Kathy T.",
    "Grassle, Jenele",
    "Gray, Charles",
    "Greening, Brian W.",
    "Grenberg, Jeanine",
    "Gross, Dana",
    "Groth, Thea",
    "Groton, Anne",
    "Haecker, Arthur",
    "Hagen, Chloe A.",
    "Hahn, Steven C.",
    "Hakim Javadi, Nooshin",
    "Hall-Holt, Olaf A.",
    "Hansen, Peter C.",
    "Hanson, Bruce",
    "Hanson, James",
    "Hanson, Marit K.",
    "Hanson, Robert",
    "Harris, Colin",
    "Hatting, Kayla R.",
    "Hauck, Robert",
    "Hawkins, Christie",
    "Hazlett, Emily A.",
    "Hazlett, Eric L.",
    "Heath, Theresa A.",
    "Heidgerken, Benjamin E.",
    "Helms, Kyle",
    "Hensrud, Tammy",
    "Hepburn, Joan",
    "Hey, Philip",
    "Hibbard, Therees",
    "Hill Cosimini, Amy M.",
    "Hodel, Martin",
    "Hodgson, Ashley",
    "Hofrenning, Daniel",
    "Holbein, Jennifer M.",
    "Holt, Ketty",
    "Howe, Timothy R.",
    "Huehn, Susan",
    "Huff, Charles",
    "Hughes, Kathleen E.",
    "Humke, Paul",
    "Humm, Courtney A.",
    "Hupton, Tara",
    "Iddrisu, Abdulai",
    "Isomura, Eri",
    "Ito, Rika",
    "Jackson, Paul T.",
    "Jacobi, Nathan M.",
    "Jensen, Elizabeth A.",
    "Jessup, David E.",
    "Johnson, Ida M.",
    "Johnson, Kenneth D.",
    "Johnson, Susie",
    "Johnston, PJ",
    "Joiner, Cassandra M.",
    "Jorgenson, Kiara",
    "Jothen, Peder J.",
    "Judge, Rebecca",
    "Kandl, Kimberly A.",
    "Kanewischer, Erica",
    "Kehrwald, Kristi A.",
    "Kheshgi, Rehanna L.",
    "Killackey, Sean P.",
    "Kim, April R.",
    "King, Bruce",
    "Klopchin, Heather J.",
    "Knobel-Piehl, Laura",
    "Kolan, Amy",
    "Kosmoski, Daniel",
    "Kruse, Dale",
    "Kucera, Karil J.",
    "Kuehn, Mary",
    "Kumagai, Natsuki",
    "Kunene, Thando L.",
    "Kutulas, Judy",
    "Kuxhausen, Anna",
    "Kwon Dobbs, Jennifer",
    "LaFond-Hudson, Sophia L.",
    "Lagerquist, L. DeAne",
    "Lane-Getaz, Sharon",
    "Larsen, Amy",
    "Lazaro Trujillo, Maria Nayeli",
    "LeBlanc, Diane C.",
    "Lee, Jerry K.",
    "Lee, Norman",
    "Leer, Elizabeth A.",
    "Lehmann, Carl",
    "Leonard, Courtney M.",
    "Lindley, Stephen T.",
    "Listenberger, Laura",
    "Loebach, Jeremy",
    "Longwich, Stacey",
    "Lott, Anthony",
    "Luckraft, Katie",
    "Luedtke, Allison O.",
    "Maeda, Dana L.",
    "Mahr, Jill",
    "Mahr, Timothy",
    "Malmgren, Jodi",
    "Marahatta, Ram",
    "Marino, Gordon D.",
    "Marlier, Elodie",
    "Marsalek, Karen E.",
    "Marsh, Jason",
    "Martagon-Geiger, Melody M.",
    "Martin, Connie",
    "Martinson, Kirk",
    "Math, Jonna M.",
    "Matsuura, Ryota",
    "Mbele, Joseph L.",
    "McBride-Harris, Jenna L.",
    "McClung, James M.",
    "McClure, Robert W.",
    "McComb, Sophia I.",
    "McCullough, Colleen",
    "McDonald, Matthew C.",
    "McKeel, James",
    "McKelvey, Steven",
    "McMillan, Donna K.",
    "Medina-Vilarino, Kristina",
    "Melby, Alyssa H.",
    "Mendez, Melissa A.",
    "Merritt, Adrienne N.",
    "Merritt, Justin W.",
    "Moeller, Johnathan R.",
    "Mohl, Emily",
    "Mokdad, Linda",
    "Montgomery, Stephanie",
    "Moore, Leslie",
    "Mooy, Anna",
    "Moreno-Diaz, Maria d.",
    "Morisette, Sandra",
    "Mugabe, Douglas",
    "Muir, Gary M.",
    "Munoz-Hutchinson, Danny",
    "Muth, Gregory W.",
    "Nagamatsu, Jeremy",
    "Naito, Jonathan T.",
    "Narvaez, Leon",
    "Neal, Diana",
    "Nelson, Daniel R.",
    "Nelson, Jane A.",
    "Nelson, Peter B.",
    "Nesbit, Scott",
    "Nordfjord, Bjorn",
    "O'Conner, Jonathan P.",
    "Odell, Margaret",
    "Ousley, Paul",
    "Paddleford, Nancy",
    "Pate, SooJin",
    "Patterson, Juliet",
    "Paul, Jason N.",
    "Pearce, Anna",
    "Perron, Kristen",
    "Peterson, Ericka K.",
    "Petok, Jessica R.",
    "Pettitt, Beth",
    "Pfarr-Baker, Rosemary A.",
    "Pinto-Handler, Sergio E.",
    "Plemons, Don Ezra C.",
    "Pollard, Vernon",
    "Porterfield, Jean C.",
    "Prehall, Andrew",
    "Quimby, Joanne",
    "Rainey, Timothy M. II.",
    "Rambachan, Anantanand",
    "Ramirez, Catherine",
    "Randall, Amanda",
    "Reece, Steve T.",
    "Reed, Barbara",
    "Richardson, Brandt A.",
    "Richey, Matthew",
    "Ripley, Jason J.",
    "Rives, Hawken M.",
    "Roback, Paul J.",
    "Roberts, Anthony",
    "Roberts, Janice",
    "Roberts, William P.",
    "Robinson, Marc",
    "Rodland, Catherine R.",
    "Roith, Joseph",
    "Rudd, Anthony J.",
    "Ryan, Hannah",
    "Sanchez Gonzalez, Rodrigo",
    "Sanford, James C.",
    "Sannes, Paula A.",
    "Santurri, Edmund",
    "Saurer, John",
    "Schalliol, David C.",
    "Schillinger, Jamie A.",
    "Schmid, Caitlin R.",
    "Schmidt, Bryan",
    "Scholz-Carlson, Miriam",
    "Schroeder, Nanette",
    "Schwehn, Kaethe",
    "Schwinefus, Jeffrey J.",
    "Scopatz, Dana K.",
    "Selinsky, Peter N.",
    "Shaiman, Jennifer",
    "Shea, Kathleen L.",
    "Shealer, Bryan T.",
    "Sheppard, Ryan R.",
    "Shih, Hsiang-Lin",
    "Shimota, Eileen",
    "Shows Jr., Wallace R.",
    "Smalling, Susan E.",
    "Smith, Kay E.",
    "Sonnega, William",
    "Sortor, Marci J.",
    "Sparks, Jillian A.",
    "Spiker, Christina",
    "Steed, Kathryn L.",
    "Stephens, Emery",
    "Strichartz, Ariel",
    "Sundby, Mark",
    "Svynarenko, Anton",
    "Swain, Corliss",
    "Swanson, Kathryn R.",
    "Swedin, Rachel K.",
    "Taliaferro, Charles",
    "Tanksley, Jason",
    "Tcacenco, Andrei",
    "Tegtmeyer Pak, Katherine S.",
    "Tegtmeyer, Judith",
    "Thalhammer, Kristina",
    "Thompson, Nancy M.",
    "Thresher, Tanya L.",
    "Titus, Mary",
    "Trull, Mary E.",
    "Tuley, Katherine A.",
    "Umbanhowar, Charles Jr.",
    "Veltri, Carlo O.",
    "Vendetti, Maria",
    "von Bibra, Anne",
    "Vosburg, Nora",
    "Walczak, Mary",
    "Wall, Travis J.",
    "Walmsley, David P.",
    "Walter, Anne",
    "Walter, Gregory A.",
    "Wambheim, Bruce",
    "Ward, Sean F.",
    "Watson, Jill A.",
    "Weeks, Michon",
    "Wells, Colin",
    "Westler, Brendon",
    "Whitman, Peter",
    "Wilkerson, Karen",
    "Williams, Arneshia L.",
    "Williamson, Thomas A.",
    "Wilson, Charles",
    "Wilson, Karen",
    "Woida, Charles A.",
    "Wondemagegnehu, Tesfa Y.",
    "Wong, Ka F.",
    "Wood, Adam C.",
    "Wright, Matthew",
    "Wright, Robin L.",
    "Yoshioka-Maxwell, Olivia C.",
    "Zhou, Ying",
    "Ziegler, Kathryn",
];
module.exports = SIS_PROFS;
